using Content.Client.UserInterface.Systems.Gameplay;
using Content.Client.UserInterface.Systems.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Hotbar.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ClothingGui : UIWidget
{
    public ClothingGui()
    {
        RobustXamlLoader.Load(this);


        var gameplayStateLoad = UserInterfaceManager.GetUIController<GameplayStateLoadController>();
        gameplayStateLoad.OnScreenLoad += OnScreenLoad;
        OnScreenLoad();
    }

    private void OnScreenLoad()
    {
        var inventoryUIController = UserInterfaceManager.GetUIController<InventoryUIController>();

        inventoryUIController.RegisterInventoryBarContainer(InventoryHotbar);
        inventoryUIController.RegisterInventoryButton(InventoryButton);
    }
}
